# Generated by Django 5.1.6 on 2025-03-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wqi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterqualitymeasurement',
            old_name='dissolved_oxygen',
            new_name='cod',
        ),
        migrations.RenameField(
            model_name='waterqualitymeasurement',
            old_name='fecal_coliform',
            new_name='do',
        ),
        migrations.RenameField(
            model_name='waterqualitymeasurement',
            old_name='nitrate',
            new_name='total_coliform',
        ),
        migrations.RemoveField(
            model_name='waterqualitymeasurement',
            name='phosphate',
        ),
        migrations.RemoveField(
            model_name='waterqualitymeasurement',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='waterqualitymeasurement',
            name='total_solids',
        ),
        migrations.RemoveField(
            model_name='waterqualitymeasurement',
            name='turbidity',
        ),
    ]
