# Generated by Django 5.1.6 on 2025-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqi_app', '0002_rename_dissolved_oxygen_waterqualitymeasurement_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterqualitymeasurement',
            name='storet_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualitymeasurement',
            name='storet_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
