# Generated by Django 5.1.6 on 2025-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqi_app', '0003_waterqualitymeasurement_storet_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterqualitymeasurement',
            old_name='storet_status',
            new_name='storet_class',
        ),
        migrations.AddField(
            model_name='waterqualitymeasurement',
            name='mamdani_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waterqualitymeasurement',
            name='storet_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waterqualitymeasurement',
            name='storet_wqi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualitymeasurement',
            name='sugeno_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitymeasurement',
            name='storet_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
