# Generated by Django 5.1.6 on 2025-04-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqi_app', '0004_rename_storet_status_waterqualitymeasurement_storet_class_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='wqi_app_loc_latitud_4be29b_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='wqi_app_loc_name_bb0341_idx'),
        ),
    ]
