# Generated by Django 5.1.6 on 2025-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqi_app', '0005_location_wqi_app_loc_latitud_4be29b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name', 'latitude', 'longitude'], name='wqi_app_loc_name_af1b86_idx'),
        ),
    ]
