# Generated by Django 5.1.6 on 2025-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqi_app', '0006_alter_location_options_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='wqi_app_loc_latitud_4be29b_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='wqi_app_loc_name_bb0341_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='wqi_app_loc_name_af1b86_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
